name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what happened..
    validations:
      required: true
  - type: textarea
    id: solutions
    attributes:
      label: Any solutions?
      description: If you have an idea on how to fix this, please add it here.
      placeholder: Tell us what you think..
  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Please add any addiotional info, such as screenshots, logs or code here. For code, use ``` backticks to get it highlighted.